594 fix debounce on all input blocks
SEMOSS/semoss-ui pull request #211
Opened 2024-07-23 18:00 UTC by phkem

2024-07-24 19:20 UTC, johbaxter commented
Will review by Friday

2024-07-26 15:33 UTC, johbaxter commented
Resolves #16

2024-07-26 16:10 UTC, phkem commented
Resolves #16

2024-07-26 16:32 UTC, phkem commented
Resolves #16

2024-07-30 16:47 UTC, neelneelneel requested changes
Some issues:
- [ ] https://react.dev/warnings/invalid-hook-call-warning

2024-07-30 16:47 UTC, neelneelneel commented on packages/client/src/components/block-defaults/checkbox-block/CheckboxBlock.tsx
> +                    debounce(() => {
This violates the rules of Hooks. See https://react.dev/warnings/invalid-hook-call-warning

2024-08-09 15:48 UTC, johbaxter commented on packages/client/src/components/block-defaults/upload-block/UploadBlock.tsx
> +    const [changedValue, setChangedValue] = useState(false);
What is the purpose of this?

2024-08-09 17:50 UTC, johbaxter commented
Just took a look again, and noticed the debounce is not triggering the callback within it.  Please test this across all the changed blocks.

2024-11-19 20:21 UTC, closed without merging