284 task admin editadd user bug fixes
SEMOSS/semoss-ui pull request #303
Opened 2024-09-27 18:13 UTC by mattfreshwaters

For issue https://github.com/SEMOSS/semoss-ui/issues/284

Regex is fixed so form doesn't think XXX-XXX- is a valid phone number, accepst (XXX) XXX-XXXX or XXX-XXX-XXXX

Now sending 'newEmail' instead of 'email' to the backend for editUser

Error messages on the editUser form are now in red

2024-09-30 13:48 UTC, johbaxter commented
![image](https://github.com/user-attachments/assets/3f377987-6c39-49dd-883b-5e356f0ae849)

Is there a reason we don't pull in email into the modal. @mattfreshwaters

2024-09-30 13:53 UTC, johbaxter commented
![image](https://github.com/user-attachments/assets/1afbc95d-3655-4ed6-bcc3-c5b229d556de)
![image](https://github.com/user-attachments/assets/0a8b2526-2ff0-491f-989b-8f460efaa94b)

@mattfreshwaters also the way we send it versus the way we receive it are totally different can we have some consistency

2024-10-01 13:46 UTC, mattfreshwaters commented
> ![image](https://private-user-images.githubusercontent.com/130101715/372112355-1afbc95d-3655-4ed6-bcc3-c5b229d556de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MDY3MzcsIm5iZiI6MTcyNzcwNjQzNywicGF0aCI6Ii8xMzAxMDE3MTUvMzcyMTEyMzU1LTFhZmJjOTVkLTM2NTUtNGVkNi1iY2MzLWM1YjIyOWQ1NTZkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQxNDI3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGU2MDUyYWJkYTlmNTVjYTE3NmE4MzE5NWQwZDllMDY1OWFiNjFhYTY5MWM1N2U0MmM5NGZmYTkxMDBlNDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9Gj-Gch7Pz7jRcMkPI-8TIdx-phvhG_F51i7LCSBP_4) ![image](https://private-user-images.githubusercontent.com/130101715/372112470-0a8b2526-2ff0-491f-989b-8f460efaa94b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MDY3MzcsIm5iZiI6MTcyNzcwNjQzNywicGF0aCI6Ii8xMzAxMDE3MTUvMzcyMTEyNDcwLTBhOGIyNTI2LTJmZjAtNDkxZi05ODliLThmNDYwZWZhYTk0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQxNDI3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTY3MGM5YzVhOGFjNTY2ZGFkMDZmMWZlYzYyNmM3MmUwMzE2ZDkxMGM5ZjcwOWU4NWRmNmZiMzRhMmIzZmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5gCQZbdQTaANEthfXsMDlrsDyvZqm0dm3UiEInpvYB0)
> 
> @mattfreshwaters also the way we send it versus the way we receive it are totally different can we have some consistency
@johbaxter 
Assuming you're referencing the phone number - yep can do that. Do we have a preference of what format? Figured for user sake it is easiest if they have different options to type in, but we can adjust and send a single format to the backend (i.e. 123-456-7890) for consistency - thoughts?.

2024-10-01 21:09 UTC, mattfreshwaters commented
@johbaxter backend PR here: https://github.com/SEMOSS/Semoss/pull/171
created an issue for it in Semoss as well - https://github.com/SEMOSS/Semoss/issues/140

2024-10-07 19:35 UTC, neelneelneel requested changes

2024-10-07 19:35 UTC, neelneelneel commented on packages/client/src/components/settings/UserAddOverlay.tsx
> +    color: 'red',
Update to the 'error' color

2024-10-07 19:35 UTC, neelneelneel commented on packages/client/src/components/settings/UserAddOverlay.tsx
> +                console.log('DING DING DING');
Remove extra console.logs

2024-10-07 20:24 UTC, mattfreshwaters commented on packages/client/src/components/settings/UserAddOverlay.tsx
> +    color: 'red',
Just changed in newest commit

2024-10-07 20:24 UTC, mattfreshwaters commented on packages/client/src/components/settings/UserAddOverlay.tsx
> +                console.log('DING DING DING');
Should be gone now

2024-10-07 20:44 UTC, neelneelneel approved these changes

2024-10-07 20:44 UTC, merged