feat(client): add a select component for predefined engine types
SEMOSS/semoss-ui pull request #322
Opened 2024-10-14 10:52 UTC by 22mayank

2024-10-28 17:22 UTC, neelneelneel requested changes
Remvo

2024-10-28 17:22 UTC, neelneelneel commented on packages/client/src/components/block-defaults/select-engine-block/config.tsx
> +        multiple: false,
Remove extra / unnecessary attributes

2024-10-28 17:22 UTC, neelneelneel commented on packages/client/src/components/block-defaults/select-engine-block/config.tsx
> +    contentMenu: [
Remove unnecessary settings

2024-10-28 17:22 UTC, neelneelneel commented on packages/client/src/components/block-defaults/select-engine-block/SelectEngineBlock.tsx
> +    data: {
Add a filter for the various catalog types.

2024-11-04 12:27 UTC, 22mayank commented
Hi Neel, I have addressed the PR feedback for removing unused attributes & unnecessary settings. The filter for various catalog is already present. ( Attached screenshot )
![image](https://github.com/user-attachments/assets/dec4ca20-033a-4d91-8c04-c793c01ed72e)

2024-11-11 18:35 UTC, neelneelneel requested changes
Few changes
- [ ] Move the call to get engines to `SelectEngineBlock.tsx`. This will enable infinite-loading
- [ ] Options can be removed, so Data should be defined as
```
export interface SelectEngineBlockDef extends BlockDef<'select-engine'> {
    widget: 'select-engine';
    data: {
        style: CSSProperties;
        label: string;
        type: string // corresponds to engine type
        value: {name:string; id:string} // corresponds to name + id
        required: boolean;
        disabled: boolean;
        hint?: string;
        loading?: boolean;
    };
}
```

2024-11-19 21:08 UTC, neelneelneel commented
@themaherkhalil  - how should this interact with engines/dependencies?

2024-12-05 19:01 UTC, neelneelneel commented
Per discussion, doesn't interact with dependencies

2025-01-21 16:18 UTC, johbaxter commented
Not a viable approach

2025-01-21 16:18 UTC, closed without merging