feat(client): add a radio group component
SEMOSS/semoss-ui pull request #342
Opened 2024-10-28 11:56 UTC by 22mayank

2024-12-04 19:30 UTC, johbaxter requested changes

2024-12-04 19:30 UTC, johbaxter commented on packages/client/src/components/block-defaults/radio-block/config.tsx
> +                            <Stack spacing={2}>
![image](https://github.com/user-attachments/assets/cb2aab23-e359-4948-bf62-c0e2fa63a51b)

We need to rethink this.  Avoid the extra step, of setting a number of options.

Why don't we just have a singular field. That allows you to add options dynamically without having to specify the amount of options. Something like this.

![image](https://github.com/user-attachments/assets/b5d70afa-dec2-4a75-8186-b67a4f559eb6)

The plus button would obviously add another option

2024-12-04 19:30 UTC, johbaxter commented on packages/client/src/components/designer/menu/default-menu.ts
> +                options: [],
Can we set a default option.

options: [
{label: ''default', value: 'no value'}
]

2024-12-04 19:30 UTC, johbaxter commented on packages/client/src/components/designer/menu/default-menu.ts
> +                optionLabel: '',
Lets get rid of optionLabel

2024-12-04 19:30 UTC, johbaxter commented on packages/client/src/components/block-defaults/radio-block/config.tsx
> +        ],
This interface for options is good, don't change this

2024-12-09 20:03 UTC, tevanburen commented
Could we give users the ability to edit (or at least delete) their options? As of right now, if I make a typo, I'd have to delete and recreate the entire component. One idea is to replace the top section with a kind-of table:

![image](https://github.com/user-attachments/assets/7c85b398-fbd1-499b-9c15-40908b55dc89)

Other implementations would work as well

2024-12-10 22:15 UTC, 22mayank commented
![image](https://github.com/user-attachments/assets/37531376-d38c-4b81-9649-1194a81037f0)


Added the Tabular format for options. Kept the Default option as disabled but can be deleted and if all the options are deleted the  Default option is recreated.

2024-12-10 22:26 UTC, johbaxter commented
> ![image](https://private-user-images.githubusercontent.com/26410204/394475603-37531376-d38c-4b81-9649-1194a81037f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4Njk3MDUsIm5iZiI6MTczMzg2OTQwNSwicGF0aCI6Ii8yNjQxMDIwNC8zOTQ0NzU2MDMtMzc1MzEzNzYtZDM4Yy00YjgxLTk2NDktMTE5NGE4MTAzN2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDIyMjMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZDMxZTU4YThjODE3NGFkZDNlNjE5OTViMGI2NGYzOGFlY2I3MWNkZjYxMWVmMjE1ZDJjYzFmMjY0MmVhYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z2Y4f3tADnw1SXPUbx8F8Fvjfp9A6Qc4LrwjujmeIQs)
> 
> Added the Tabular format for options. Kept the Default option as disabled but can be deleted and if all the options are deleted the Default option is recreated.

Why did we get rid of the setting for selected value.

Also please no restrictions on options should be done.  

Think about how you would like to use it.

If you drag a radio group in, you want to edit the options (no limitations) whether it be deleting an option, adding a new one in, as well as resetting properties on those options

2024-12-11 15:01 UTC, johbaxter commented
@22mayank you got to test man.  I click radio group i add options, then i click away from radio group, then click back into radio group, all the options i created i set disappear other than the first

2024-12-11 19:17 UTC, johbaxter approved these changes

2024-12-11 19:21 UTC, merged