Vector Db file Download
SEMOSS/semoss-ui pull request #387
Opened 2024-11-18 11:48 UTC by rsatiz

2024-11-26 21:39 UTC, johbaxter commented
![image](https://github.com/user-attachments/assets/f26c3be1-1c03-4844-972f-26cd7de2cbc4)

Hey we don't even have a FileDownload reactor, curious where did you get this from.

I would merge no problem if it used the correct reactor.

@rsatiz 

_Update: If there is a PR that is dependent on a backend pr, please reference the backend issue/pr on this ticket.  Helps avoid confusion when things are not working._

Dependent on: https://github.com/SEMOSS/Semoss/pull/223

2024-12-04 05:28 UTC, rsatiz commented
@johbaxter I have developed a File download Reactor newly hence created this request.

Here is the link for the java reactor PR link for your reference https://github.com/SEMOSS/Semoss/pull/223

2024-12-04 19:42 UTC, johbaxter requested changes
Dependent on backend PR [#223](https://github.com/SEMOSS/Semoss/pull/223)

2024-12-10 20:10 UTC, johbaxter approved these changes

2024-12-10 20:10 UTC, merged